version: "2"         # required to adjust maintainability checks
exclude_patterns:
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "test/"
  - "**/vendor/"
  - "php/hamle/Grammar/Parser.php"
