build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: XDEBUG_MODE=coverage composer test
            coverage:
              file: coverage.xml   # <- Set this to where we find the coverage data.
              #    The path is relative to the current directory.
              format: clover
tools:
  external_code_coverage: true
filter:
  excluded_paths:
    - 'test/*'
checks:
  php: true
coding_style:
  php:
    indentation:
      general:
        size: 2
