# Configuration file for unit test runner.
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
#before_script:
#  - cd test/php
script: phpunit test/php --coverage-clover=coverage.xml
notifications:
  email: true
after_success:
    - bash <(curl -s https://codecov.io/bash)