# Configuration file for unit test runner.
language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
matrix:
  allow_failures:
before_script:
  - composer install
script: composer test
notifications:
  email: true
after_success:
    - bash <(curl -s https://codecov.io/bash)
sudo: false
