# Configuration file for unit test runner.
language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
matrix:
  allow_failures:
    php:
      - 5.3
      - hhvm
#before_script:
#  - cd test/php
script: phpunit test/php
notifications:
  email: false
