# Configuration file for unit test runner.
language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 7.0
#  - 5.3
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
#before_script:
#  - cd test/php
script: phpunit test/php
notifications:
  email: false
