# Configuration file for unit test runner.
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
script: composer test
notifications:
  email: true
after_success:
    - bash <(curl -s https://codecov.io/bash)
sudo: false
